---
title: "Lab3_Ridge_Regression"
author: "quan le"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load in ozone data (taken from "cosso" R package)
ozone = read.csv("data/ozone.csv")

#take a look at the data
plot(ozone,pch=16,cex=.5)
```


```{r}
#######################
#ridge regression

n = nrow(ozone)
Y = as.numeric(ozone[,1]); Y = Y - mean(Y)
X = as.matrix(ozone[,-1]); X = scale(X,center=T,scale=T)

#ridge regression solution
lam1 = 1
lam2 = 10

betals = solve(t(X)%*%X)%*%t(X)%*%Y
betar1 = solve(t(X)%*%X/n + diag(rep(lam1,8)))%*%t(X)%*%Y/n
betar2 = solve(t(X)%*%X/n + diag(rep(lam2,8)))%*%t(X)%*%Y/n
cbind(betals,betar1,betar2)
```


```{r}
#ridge regression coefficient paths
lambdas = exp(seq(log(.01),log(100),l=100))
betasr = matrix(0,length(lambdas),8)
for(i in 1:length(lambdas))
{
  betasr[i,] = solve(t(X)%*%X/n + diag(rep(lambdas[i],8)))%*%t(X)%*%Y/n
}

plot(range(lambdas),range(betasr),log="x",type="n",ylab="Coefficients",xlab="Log Lambda",xlim=c(max(lambdas),min(lambdas)))
for(j in 1:8)
{
  lines(lambdas,betasr[,j],type="l",col=j)
}
legend(max(lambdas),3.8,legend=names(ozone)[2:9],col=1:9,lty=rep(1,9))
```
