---
title: "Lab4"
author: "quan le"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(MASS)
library(leaps)
library(glmnet)

#load in ozone data (taken from "cosso" R package)
ozone = read.csv("data/ozone.csv")
```


# Algorithmic Approaches
- best subsets
- forward and backward stepwise


```{r}
#Algorithmic

#best subsets selection
fitbsub = regsubsets(x=ozone[,2:9],y=ozone[,1])
summary(fitbsub)
# Explanation: an asterisk specifies that a given variable is included in the corresponding model

# Question: Which model among these would you choose?
# Food for thought: https://en.wikipedia.org/wiki/All_models_are_wrong

res.sum <- summary(fitbsub)
data.frame(
  Adj.R2 = which.max(res.sum$adjr2),
  CP = which.min(res.sum$cp),
  BIC = which.min(res.sum$bic)
)
```


```{r}
#forward step-wise  - via AIC
fit0 = lm(ozone~1,data=ozone)
fitf = stepAIC(fit0,scope=ozone~wind+temp+invHt+press+hum+vis+milPress+invTemp,direction="forward",data=ozone,k=log(nrow(ozone)))
summary(fitf)
```


```{r}
#backwards step-wise - via AIC
fit = lm(ozone~.,data=ozone)
fitb = stepAIC(fit,direction="backward",data=ozone,k=log(nrow(ozone)))
summary(fitb)
```

# L1 Regularization

```{r}
#L1 Regularization

Y = as.numeric(ozone[,1]); Y = Y - mean(Y)
X = as.matrix(ozone[,-1]); X = scale(X,center=T,scale=T)
fit0 = lm(Y~X-1)


lam = 1
fitl = glmnet(x=X,y=Y,family="gaussian",lambda=lam,alpha=1)
cbind(fit0$coef,as.matrix(fitl$beta))
```


```{r}
#lasso paths
fitl = glmnet(x=X,y=Y,family="gaussian",alpha=1)
plot(fitl,col=1:8)
legend(0,4,legend=names(ozone)[2:9],col=1:8,lty=rep(1,8),cex=.8)
```

