---
title: "Lab5_Lasso"
author: "quan le"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(glmnet)

#load in ozone data (taken from "cosso" R package)
ozone = read.csv("data/ozone.csv")
```


```{r}
# L1 Regularization

Y = as.numeric(ozone[,1]); Y = Y - mean(Y)
X = as.matrix(ozone[,-1]); X = scale(X,center=T,scale=T)
fit0 = lm(Y~X-1)

lam1 = 1
lam2 = 3
fitl1 = glmnet(x=X,y=Y,family="gaussian",lambda=lam1,alpha=1)
fitl2 = glmnet(x=X,y=Y,family="gaussian",lambda=lam2,alpha=1)

# coefficients for lambda = 0, 1, 3
cbind(fit0$coef,as.matrix(fitl1$beta),as.matrix(fitl2$beta))
```


```{r}
#lasso paths
fitl = glmnet(x=X,y=Y,family="gaussian",alpha=1)
plot(fitl,col=1:8)
legend(0,4,legend=names(ozone)[2:9],col=1:8,lty=rep(1,8),cex=.8)

#elastic net paths
fite = glmnet(x=X,y=Y,family="gaussian",alpha=0.66)
plot(fite,col=1:8)
legend(0,4,legend=names(ozone)[2:9],col=1:8,lty=rep(1,8),cex=.8)

fite = glmnet(x=X,y=Y,family="gaussian",alpha=0.33)
plot(fite,col=1:8)
legend(0,4,legend=names(ozone)[2:9],col=1:8,lty=rep(1,8),cex=.8)

#ridge paths
fitr = glmnet(x=X,y=Y,family="gaussian",alpha=0)
plot(fitr,col=1:8)
legend(0,3,legend=names(ozone)[2:9],col=1:8,lty=rep(1,8),cex=.8)
```
