---
title: "Lab 6 Cross Validation"
author: "quan le"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glmnet)
library(ISLR)

x=model.matrix(Salary~.,Hitters)[,-1]
y=na.omit(Hitters$Salary)

set.seed(1)
train=sample(1:nrow(x), nrow(x)/2)
test=(-train)
```


```{r}
# k-fold cross validation is a technique where the dataset is split into k
# subsets. (k-1) subsets are used for training the model and the remaining 1
# subset for testing the model. This is repeated k times, so that each subset 
# serves as the test set once.

grid=exp(1)^seq(10,-1,length=100) # the sequence of lambda

alpha = 0.0

# manual cross validation
nfolds = 5
foldsize = floor(length(train)/nfolds)

avgMSE = 0
for (i in 1:nfolds) {
  fold = seq((i-1)*foldsize, i*foldsize)
  fit = glmnet(x[train,][-fold,], y[train][-fold], alpha=alpha, lambda=grid)
  assessment = assess.glmnet(fit, x[train,][fold,], y[train][fold])
  avgMSE = avgMSE + assessment$mse
}
avgMSE = avgMSE/nfolds

fit = glmnet(x[train,], y[train], type.measure = "mse", alpha=alpha, lambda=grid)
e.train = colMeans((y[train] - predict(fit, newx = x[train,]))**2)
e.test = colMeans((y[test] - predict(fit, newx = x[test,]))**2)
```


```{r}
# plots
plot(log(grid), avgMSE, main=paste("MSE for ",nfolds, "-fold cross validation", sep=""), 
     xlab="log(lambda)",
     ylab="MSE",
     ylim=c(50000,200000),
     type="l")
lines(log(grid), e.test, col="red")
lines(log(grid), e.train, col="blue")
legend(x=7, y=90000, c("cv error", "test error", "training error"),
       col=c("black", "red", "blue"), lty=rep(1,3))
```


```{r}
# cross validation via cv.glmnet
cvfit = cv.glmnet(x[train,], y[train], alpha = alpha,lambda=grid, nfolds=5)
plot(cvfit)
title("MSE for nfolds = 3", line = 2)

cvfit = cv.glmnet(x[train,], y[train], alpha = alpha,lambda=grid, nfolds=10)
plot(cvfit)
title("MSE for nfolds = 10", line = 2)

cvfit = cv.glmnet(x[train,], y[train], alpha = alpha,lambda=grid, nfolds=length(train))
plot(cvfit)
title("MSE for nfolds = n = 131 (LOOCV)", line = 2)
```


